DROP DATABASE pokemon;
CREATE DATABASE pokemon;
\c pokemon;

--
-- Table structure for table pokemon
--

CREATE TABLE IF NOT EXISTS pokemon (
  ID serial NOT NULL,
  name varchar(35)  NOT NULL,
  weight decimal NOT NULL,
  height decimal NOT NULL,
  male decimal NOT NULL,
  female decimal NOT NULL,
  PRIMARY KEY  (ID)
) ;

--
-- Dumping data for table pokemon
--
-- ORDER BY:  ID
-- INSERT INTO pokemon (name, weight, height, male, female)  VALUES ();
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Bulbasaur', 15.2, 2.04, 87.5, 12.5);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Ivysaur', 28.7, 3.03, 87.5, 12.5);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Venusaur', 220.5, 6.07, 87.5, 12.5);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Charmander', 18.7, 2.00, 87.5, 12.5);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Charmeleon', 41.9, 3.07, 87.5, 12.5);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Charizard', 199.5, 5.07, 87.5, 12.5);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Squirtle', 19.8, 1.08, 87.5, 12.5);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Wartortle', 49.6, 3.03, 87.5, 12.5);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Blastoise', 188.5, 5.03, 87.5, 12.5);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Caterpie', 6.4, 1.00, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Metapod', 21.8, 2.04, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Butterfree', 70.5, 3.07, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Weedle', 7.1, 1.00, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Kakuna', 22.0, 2.00, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Beedrill', 65.0, 3.03, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Pidgey', 4.0, 1.00, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Pidgeotto', 66.1, 3.07, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Pidgeot', 87.1, 4.11, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Rattata', 7.7, 1.00, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Raticate', 40.8, 2.04, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Spearow', 4.4, 1.00, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Fearow', 83.8, 3.11, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Ekans', 15.2, 6.07, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Arbok', 143.3, 11.06, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Pikachu', 13.2, 1.04, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Raichi', 66.1, 2.07, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Sandshrew', 26.5, 2.00, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Sandslash', 65.0, 3.03, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Nidoran', 15.4, 1.04, 0.0, 100.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Nidorina', 44.1, 2.07, 0.0, 100.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Nidoqueen', 132.3, 4.03, 0.0, 100.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Nidoran', 19.8, 1.07, 100.0, 0.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Nidorino', 43.0, 2.11, 100.0, 0.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Nidoking', 136.7, 4.07, 100.0, 0.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Clefairy', 16.5, 2.00, 25.0, 75.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Clefable', 88.2, 4.03, 25.0, 75.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Vulpix', 21.8, 2.00, 25.0, 75.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Ninetails', 43.9, 3.07, 25.0, 75.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Jigglypuff', 12.1, 1.08, 25.0, 75.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('wigglytuff', 26.5, 3.03, 25.0, 75.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Zubat', 16.5, 2.07, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Golbat', 121.3, 5.03, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Oddish', 11.9, 1.08, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Gloom', 19.0, 2.07, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Vileplum', 41.0, 3.11, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Paras', 11.9, 1.00, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Parasect', 65.0, 3.03, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Venonat', 66.1, 3.03, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Venomoth', 27.6, 4.11, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Diglett', 1.8, 0.08, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Dugtrio', 73.4, 2.04, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Meowth', 9.3, 1.04, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Persian', 70.6, 3.03, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Psyduck', 43.2, 2.07, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Golduck', 168.9, 5.07, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Mankey', 61.7, 1.08, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Primeape', 70.5, 3.03, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Growlithe', 41.9, 2.04, 75.0, 25.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Arcanine', 341.7, 6.03, 75.0, 25.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Poliwag', 27.3, 2.00, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Poliwhirl', 44.0, 3.03, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Poliwrath', 119.0, 4.03, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Abra', 43.0, 2.11, 75.0, 25.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Kadabra', 124.6, 4.03, 75.0, 25.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Alakazam', 105.8, 4.11, 75.0, 25.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Machop', 43.0, 2.07, 75.0, 25.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Machoke', 155.0, 4.11, 75.0, 25.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Machamp', 286.6, 5.03, 75.0, 75.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Bellsprout', 8.8, 2.04, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Weepinbell', 14.1, 3.03, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Victreebel', 34.2, 5.07, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Tentacool', 100.3, 2.11, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Tentacruel', 121.3, 5.03, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Geodude', 44.1, 1.04, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Graveler', 231.5, 3.03, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Golem', 661.4, 4.07, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Ponyta', 66.1, 3.03, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Rapidash', 209.4, 5.07, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Slowpoke', 79.4, 3.11, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Slowbro', 173.1, 5.03, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Magnemite', 13.2, 1.00, 0.0, 0.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Magneton', 132.3, 3.03, 0.0, 0.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Farfetch''d', 33.1, 2.07, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Doduo', 86.4, 4.07, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Dodrio', 187.8, 5.11, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Seel', 198.4, 3.07, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Dewgong', 264.6, 5.07, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Grimer', 66.1, 2.11, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Muk', 66.1, 3.11, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Shellder', 8.8, 1.00, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Cloyster', 292.1, 4.11, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Gastly', 0.2, 4.03, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Haunter', 0.2, 5.03, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Gengar', 89.3, 4.11, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Onix', 463.0, 28.10, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Drowzee', 71.4, 3.03, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Hypno', 166.7, 5.03, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Krabby', 14.9, 1.04, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Kingler', 132.3, 4.03, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Voltorb', 22.9, 1.08, 0.0, 0.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Electrode', 146.8, 3.11, 0.0, 0.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Exeggcute', 5.5, 1.04, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Exeggutor', 264.6, 6.07, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Cubone', 14.3, 1.04, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Marowak', 99.2, 3.03, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Hitmonlee', 109.8, 4.11, 100.0, 0.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Hitmonchan', 110.7, 4.07, 100.0, 0.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Lickitung', 144.4, 3.11, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Koffing', 2.2, 2.00, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Weezing', 20.9, 3.11, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Rhyhorn', 253.5, 3.03, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Rhydon', 264.6, 6.03, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Chansey', 76.3, 3.07, 0.0, 100.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Tangela', 77.2, 3.03, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Kangaskhan', 176.4, 7.03, 0.0, 100.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Horsea', 17.6, 1.04, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Seadra', 55.1, 3.11, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Goldeen', 33.1, 2.00, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Seaking', 86.0, 4.03, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Staryu', 76.1, 2.07, 0.0, 0.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Starmie', 176.4, 3.07, 0.0, 0.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Mr. Mime', 120.1, 4.03, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Scyther', 123.5, 4.11, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Jynx', 89.5, 4.07, 0.0, 100.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Electabuzz', 66.1, 3.07, 75.0, 25.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Magmar', 98.1, 4.03, 75.0, 25.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Pinsir', 121.3, 4.11, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Tauros', 194.9, 4.07, 100.0, 0.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Magikarp', 22.0, 2.11, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Gyarados', 518.1, 21.04, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Lapras', 485.0, 8.02, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Ditto', 8.8, 1.00, 0.0, 0.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Eevee', 14.3, 1.00, 87.5, 12.5);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Vaporeon', 29.0, 1.0, 87.5, 12.5);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Jolteon', 54.0, 2.07, 87.5, 12.5);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Flareon', 55.1, 2.11, 87.5, 12.5);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Porygon', 80.5, 2.07, 0.0, 0.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Omanyte', 16.5, 1.05, 87.5, 12.5);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Omastar', 77.2, 3.03, 87.5, 12.5);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Kabuto', 25.4, 1.08, 87.5, 12.5);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Kabutops', 89.3, 4.03, 87.5, 12.5);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Aerodactyl', 130.1, 5.11, 87.5, 12.5);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Snorlax', 1014.1, 6.11, 87.5, 12.5);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Articuno', 122.1, 5.07, 0.0, 0.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Zapdos', 116.0, 5.03, 0.0, 0.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Moltres', 132.3, 6.07, 0.0, 0.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Dratini', 7.3, 5.11, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Dragonair', 36.4, 13.01, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Dragonite', 463.0, 7.03, 50.0, 50.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Mewtwo', 269.0, 6.07, 0.0, 0.0);
INSERT INTO pokemon (name, weight, height, male, female)  VALUES ('Mew', 8.8, 1.04, 0.0, 0.0);

CREATE TABLE IF NOT EXISTS PossibleTypes (
  ID serial NOT NULL,
  nameoftype varchar(35)  NOT NULL,
  PRIMARY KEY  (ID)
) ;

INSERT INTO PossibleTypes (nameoftype) VALUES ('bug');
INSERT INTO PossibleTypes (nameoftype) VALUES ('dragon');
INSERT INTO PossibleTypes (nameoftype) VALUES ('ice');
INSERT INTO PossibleTypes (nameoftype) VALUES ('fighting');
INSERT INTO PossibleTypes (nameoftype) VALUES ('fire');
INSERT INTO PossibleTypes (nameoftype) VALUES ('flying');
INSERT INTO PossibleTypes (nameoftype) VALUES ('grass');
INSERT INTO PossibleTypes (nameoftype) VALUES ('ghost');
INSERT INTO PossibleTypes (nameoftype) VALUES ('ground');
INSERT INTO PossibleTypes (nameoftype) VALUES ('electric');
INSERT INTO PossibleTypes (nameoftype) VALUES ('normal');
INSERT INTO PossibleTypes (nameoftype) VALUES ('poison');
INSERT INTO PossibleTypes (nameoftype) VALUES ('psychic');
INSERT INTO PossibleTypes (nameoftype) VALUES ('rock');
INSERT INTO PossibleTypes (nameoftype) VALUES ('water');
INSERT INTO PossibleTypes (nameoftype) VALUES ('steel');

CREATE TABLE IF NOT EXISTS types (
  poke_ID INT NOT NULL,
  type_ID INT NOT NULL,
  FOREIGN KEY(poke_ID)
  REFERENCES pokemon(ID),
  FOREIGN KEY(type_ID)
  REFERENCES PossibleTypes(ID)
);

INSERT INTO types (poke_ID, type_ID) VALUES (1, 7);
INSERT INTO types (poke_ID, type_ID) VALUES (1, 12);
INSERT INTO types (poke_ID, type_ID) VALUES (2, 7);
INSERT INTO types (poke_ID, type_ID) VALUES (2, 12);
INSERT INTO types (poke_ID, type_ID) VALUES (3, 7);
INSERT INTO types (poke_ID, type_ID) VALUES (3, 12);
INSERT INTO types (poke_ID, type_ID) VALUES (4, 5);
INSERT INTO types (poke_ID, type_ID) VALUES (5, 5);
INSERT INTO types (poke_ID, type_ID) VALUES (6, 5);
INSERT INTO types (poke_ID, type_ID) VALUES (6, 6);
INSERT INTO types (poke_ID, type_ID) VALUES (7, 15);
INSERT INTO types (poke_ID, type_ID) VALUES (8, 15);
INSERT INTO types (poke_ID, type_ID) VALUES (9, 15);
INSERT INTO types (poke_ID, type_ID) VALUES (10, 1);
INSERT INTO types (poke_ID, type_ID) VALUES (11, 1);
INSERT INTO types (poke_ID, type_ID) VALUES (12, 1);
INSERT INTO types (poke_ID, type_ID) VALUES (12, 6);
INSERT INTO types (poke_ID, type_ID) VALUES (13, 1);
INSERT INTO types (poke_ID, type_ID) VALUES (13, 12);
INSERT INTO types (poke_ID, type_ID) VALUES (14, 1);
INSERT INTO types (poke_ID, type_ID) VALUES (14, 12);
INSERT INTO types (poke_ID, type_ID) VALUES (15, 1);
INSERT INTO types (poke_ID, type_ID) VALUES (15, 12);
INSERT INTO types (poke_ID, type_ID) VALUES (16, 11);
INSERT INTO types (poke_ID, type_ID) VALUES (16, 6);
INSERT INTO types (poke_ID, type_ID) VALUES (17, 11);
INSERT INTO types (poke_ID, type_ID) VALUES (17, 6);
INSERT INTO types (poke_ID, type_ID) VALUES (18, 11);
INSERT INTO types (poke_ID, type_ID) VALUES (18, 6);
INSERT INTO types (poke_ID, type_ID) VALUES (19, 11);
INSERT INTO types (poke_ID, type_ID) VALUES (20, 11);
INSERT INTO types (poke_ID, type_ID) VALUES (21, 11);
INSERT INTO types (poke_ID, type_ID) VALUES (32, 12);
INSERT INTO types (poke_ID, type_ID) VALUES (22, 11);
INSERT INTO types (poke_ID, type_ID) VALUES (22, 6);
INSERT INTO types (poke_ID, type_ID) VALUES (23, 12);
INSERT INTO types (poke_ID, type_ID) VALUES (24, 12);
INSERT INTO types (poke_ID, type_ID) VALUES (25, 10);
INSERT INTO types (poke_ID, type_ID) VALUES (26, 10);
INSERT INTO types (poke_ID, type_ID) VALUES (27, 9);
INSERT INTO types (poke_ID, type_ID) VALUES (28, 9);
INSERT INTO types (poke_ID, type_ID) VALUES (29, 12);
INSERT INTO types (poke_ID, type_ID) VALUES (30, 12);
INSERT INTO types (poke_ID, type_ID) VALUES (31, 12);
INSERT INTO types (poke_ID, type_ID) VALUES (31, 9);
INSERT INTO types (poke_ID, type_ID) VALUES (32, 12);
INSERT INTO types (poke_ID, type_ID) VALUES (33, 12);
INSERT INTO types (poke_ID, type_ID) VALUES (34, 12);
INSERT INTO types (poke_ID, type_ID) VALUES (34, 9);
INSERT INTO types (poke_ID, type_ID) VALUES (35, 11);
INSERT INTO types (poke_ID, type_ID) VALUES (36, 11);
INSERT INTO types (poke_ID, type_ID) VALUES (37, 5);
INSERT INTO types (poke_ID, type_ID) VALUES (38, 5);
INSERT INTO types (poke_ID, type_ID) VALUES (39, 11);
INSERT INTO types (poke_ID, type_ID) VALUES (40, 11);
INSERT INTO types (poke_ID, type_ID) VALUES (41, 12);
INSERT INTO types (poke_ID, type_ID) VALUES (41, 6);
INSERT INTO types (poke_ID, type_ID) VALUES (42, 12);
INSERT INTO types (poke_ID, type_ID) VALUES (42, 6);
INSERT INTO types (poke_ID, type_ID) VALUES (43, 12);
INSERT INTO types (poke_ID, type_ID) VALUES (43, 7);
INSERT INTO types (poke_ID, type_ID) VALUES (44, 12);
INSERT INTO types (poke_ID, type_ID) VALUES (44, 12);
INSERT INTO types (poke_ID, type_ID) VALUES (45, 12);
INSERT INTO types (poke_ID, type_ID) VALUES (45, 7);
INSERT INTO types (poke_ID, type_ID) VALUES (46, 1);
INSERT INTO types (poke_ID, type_ID) VALUES (46, 7);
INSERT INTO types (poke_ID, type_ID) VALUES (47, 1);
INSERT INTO types (poke_ID, type_ID) VALUES (47, 7);
INSERT INTO types (poke_ID, type_ID) VALUES (48, 1);
INSERT INTO types (poke_ID, type_ID) VALUES (48, 12);
INSERT INTO types (poke_ID, type_ID) VALUES (49, 1);
INSERT INTO types (poke_ID, type_ID) VALUES (49, 12);
INSERT INTO types (poke_ID, type_ID) VALUES (50, 9);
INSERT INTO types (poke_ID, type_ID) VALUES (51, 9);
INSERT INTO types (poke_ID, type_ID) VALUES (52, 11);
INSERT INTO types (poke_ID, type_ID) VALUES (53, 11);
INSERT INTO types (poke_ID, type_ID) VALUES (54, 15);
INSERT INTO types (poke_ID, type_ID) VALUES (55, 15);
INSERT INTO types (poke_ID, type_ID) VALUES (56, 4);
INSERT INTO types (poke_ID, type_ID) VALUES (57, 4);
INSERT INTO types (poke_ID, type_ID) VALUES (58, 5);
INSERT INTO types (poke_ID, type_ID) VALUES (59, 5);
INSERT INTO types (poke_ID, type_ID) VALUES (60, 15);
INSERT INTO types (poke_ID, type_ID) VALUES (61, 15);
INSERT INTO types (poke_ID, type_ID) VALUES (62, 15);
INSERT INTO types (poke_ID, type_ID) VALUES (62, 4);
INSERT INTO types (poke_ID, type_ID) VALUES (63, 13);
INSERT INTO types (poke_ID, type_ID) VALUES (64, 13);
INSERT INTO types (poke_ID, type_ID) VALUES (65, 13);
INSERT INTO types (poke_ID, type_ID) VALUES (66, 4);
INSERT INTO types (poke_ID, type_ID) VALUES (67, 4);
INSERT INTO types (poke_ID, type_ID) VALUES (68, 4);
INSERT INTO types (poke_ID, type_ID) VALUES (69, 12);
INSERT INTO types (poke_ID, type_ID) VALUES (69, 7);
INSERT INTO types (poke_ID, type_ID) VALUES (70, 12);
INSERT INTO types (poke_ID, type_ID) VALUES (70, 7);
INSERT INTO types (poke_ID, type_ID) VALUES (71, 12);
INSERT INTO types (poke_ID, type_ID) VALUES (71, 7);
INSERT INTO types (poke_ID, type_ID) VALUES (72, 12);
INSERT INTO types (poke_ID, type_ID) VALUES (72, 15);
INSERT INTO types (poke_ID, type_ID) VALUES (73, 12);
INSERT INTO types (poke_ID, type_ID) VALUES (73, 15);
INSERT INTO types (poke_ID, type_ID) VALUES (74, 9);
INSERT INTO types (poke_ID, type_ID) VALUES (74, 14);
INSERT INTO types (poke_ID, type_ID) VALUES (75, 9);
INSERT INTO types (poke_ID, type_ID) VALUES (75, 14);
INSERT INTO types (poke_ID, type_ID) VALUES (76, 9);
INSERT INTO types (poke_ID, type_ID) VALUES (76, 14);
INSERT INTO types (poke_ID, type_ID) VALUES (77, 5);
INSERT INTO types (poke_ID, type_ID) VALUES (78, 5);
INSERT INTO types (poke_ID, type_ID) VALUES (79, 15);
INSERT INTO types (poke_ID, type_ID) VALUES (79, 13);
INSERT INTO types (poke_ID, type_ID) VALUES (80, 15);
INSERT INTO types (poke_ID, type_ID) VALUES (80, 13);
INSERT INTO types (poke_ID, type_ID) VALUES (81, 10);
INSERT INTO types (poke_ID, type_ID) VALUES (81, 16);
INSERT INTO types (poke_ID, type_ID) VALUES (82, 10);
INSERT INTO types (poke_ID, type_ID) VALUES (82, 16);
INSERT INTO types (poke_ID, type_ID) VALUES (83, 11);
INSERT INTO types (poke_ID, type_ID) VALUES (83, 6);
INSERT INTO types (poke_ID, type_ID) VALUES (84, 11);
INSERT INTO types (poke_ID, type_ID) VALUES (84, 6);
INSERT INTO types (poke_ID, type_ID) VALUES (85, 11);
INSERT INTO types (poke_ID, type_ID) VALUES (85, 6);
INSERT INTO types (poke_ID, type_ID) VALUES (86, 15);
INSERT INTO types (poke_ID, type_ID) VALUES (87, 15);
INSERT INTO types (poke_ID, type_ID) VALUES (87, 3);
INSERT INTO types (poke_ID, type_ID) VALUES (88, 12);
INSERT INTO types (poke_ID, type_ID) VALUES (89, 12);
INSERT INTO types (poke_ID, type_ID) VALUES (90, 15);
INSERT INTO types (poke_ID, type_ID) VALUES (91, 15);
INSERT INTO types (poke_ID, type_ID) VALUES (91, 3);
INSERT INTO types (poke_ID, type_ID) VALUES (92, 12);
INSERT INTO types (poke_ID, type_ID) VALUES (92, 8);
INSERT INTO types (poke_ID, type_ID) VALUES (93, 12);
INSERT INTO types (poke_ID, type_ID) VALUES (93, 8);
INSERT INTO types (poke_ID, type_ID) VALUES (94, 12);
INSERT INTO types (poke_ID, type_ID) VALUES (94, 8);
INSERT INTO types (poke_ID, type_ID) VALUES (95, 14);
INSERT INTO types (poke_ID, type_ID) VALUES (95, 9);
INSERT INTO types (poke_ID, type_ID) VALUES (96, 13);
INSERT INTO types (poke_ID, type_ID) VALUES (97, 13);
INSERT INTO types (poke_ID, type_ID) VALUES (98, 15);
INSERT INTO types (poke_ID, type_ID) VALUES (99, 15);
INSERT INTO types (poke_ID, type_ID) VALUES (100, 10);
INSERT INTO types (poke_ID, type_ID) VALUES (101, 10);
INSERT INTO types (poke_ID, type_ID) VALUES (102, 7);
INSERT INTO types (poke_ID, type_ID) VALUES (102, 13);
INSERT INTO types (poke_ID, type_ID) VALUES (103, 7);
INSERT INTO types (poke_ID, type_ID) VALUES (103, 13);
INSERT INTO types (poke_ID, type_ID) VALUES (104, 9);
INSERT INTO types (poke_ID, type_ID) VALUES (105, 9);
INSERT INTO types (poke_ID, type_ID) VALUES (106, 4);
INSERT INTO types (poke_ID, type_ID) VALUES (107, 4);
INSERT INTO types (poke_ID, type_ID) VALUES (108, 11);
INSERT INTO types (poke_ID, type_ID) VALUES (109, 12);
INSERT INTO types (poke_ID, type_ID) VALUES (110, 12);
INSERT INTO types (poke_ID, type_ID) VALUES (111, 9);
INSERT INTO types (poke_ID, type_ID) VALUES (111, 14);
INSERT INTO types (poke_ID, type_ID) VALUES (112, 9);
INSERT INTO types (poke_ID, type_ID) VALUES (112, 14);
INSERT INTO types (poke_ID, type_ID) VALUES (123, 1);
INSERT INTO types (poke_ID, type_ID) VALUES (114, 7);
INSERT INTO types (poke_ID, type_ID) VALUES (115, 11);
INSERT INTO types (poke_ID, type_ID) VALUES (116, 15);
INSERT INTO types (poke_ID, type_ID) VALUES (117, 15);
INSERT INTO types (poke_ID, type_ID) VALUES (118, 15);
INSERT INTO types (poke_ID, type_ID) VALUES (119, 15);
INSERT INTO types (poke_ID, type_ID) VALUES (120, 15);
INSERT INTO types (poke_ID, type_ID) VALUES (121, 15);
INSERT INTO types (poke_ID, type_ID) VALUES (121, 13);
INSERT INTO types (poke_ID, type_ID) VALUES (122, 13);
INSERT INTO types (poke_ID, type_ID) VALUES (123, 1);
INSERT INTO types (poke_ID, type_ID) VALUES (123, 6);
INSERT INTO types (poke_ID, type_ID) VALUES (124, 3);
INSERT INTO types (poke_ID, type_ID) VALUES (124, 13);
INSERT INTO types (poke_ID, type_ID) VALUES (125, 10);
INSERT INTO types (poke_ID, type_ID) VALUES (126, 5);
INSERT INTO types (poke_ID, type_ID) VALUES (127, 1);
INSERT INTO types (poke_ID, type_ID) VALUES (128, 11);
INSERT INTO types (poke_ID, type_ID) VALUES (129, 15);
INSERT INTO types (poke_ID, type_ID) VALUES (130, 15);
INSERT INTO types (poke_ID, type_ID) VALUES (130, 6);
INSERT INTO types (poke_ID, type_ID) VALUES (131, 15);
INSERT INTO types (poke_ID, type_ID) VALUES (131, 3);
INSERT INTO types (poke_ID, type_ID) VALUES (132, 11);
INSERT INTO types (poke_ID, type_ID) VALUES (133, 11);
INSERT INTO types (poke_ID, type_ID) VALUES (134, 15);
INSERT INTO types (poke_ID, type_ID) VALUES (135, 10);
INSERT INTO types (poke_ID, type_ID) VALUES (136, 5);
INSERT INTO types (poke_ID, type_ID) VALUES (137, 11);
INSERT INTO types (poke_ID, type_ID) VALUES (138, 14);
INSERT INTO types (poke_ID, type_ID) VALUES (138, 15);
INSERT INTO types (poke_ID, type_ID) VALUES (139, 14);
INSERT INTO types (poke_ID, type_ID) VALUES (139, 15);
INSERT INTO types (poke_ID, type_ID) VALUES (140, 14);
INSERT INTO types (poke_ID, type_ID) VALUES (140, 15);
INSERT INTO types (poke_ID, type_ID) VALUES (141, 14);
INSERT INTO types (poke_ID, type_ID) VALUES (141, 15);
INSERT INTO types (poke_ID, type_ID) VALUES (142, 14);
INSERT INTO types (poke_ID, type_ID) VALUES (142, 6);
INSERT INTO types (poke_ID, type_ID) VALUES (143, 11);
INSERT INTO types (poke_ID, type_ID) VALUES (144, 6);
INSERT INTO types (poke_ID, type_ID) VALUES (144, 3);
INSERT INTO types (poke_ID, type_ID) VALUES (145, 6);
INSERT INTO types (poke_ID, type_ID) VALUES (145, 10);
INSERT INTO types (poke_ID, type_ID) VALUES (146, 6);
INSERT INTO types (poke_ID, type_ID) VALUES (146, 5);
INSERT INTO types (poke_ID, type_ID) VALUES (147, 2);
INSERT INTO types (poke_ID, type_ID) VALUES (148, 2);
INSERT INTO types (poke_ID, type_ID) VALUES (149, 2);
INSERT INTO types (poke_ID, type_ID) VALUES (149, 6);
INSERT INTO types (poke_ID, type_ID) VALUES (150, 13);
INSERT INTO types (poke_ID, type_ID) VALUES (151, 13);




